[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "liquidpy"
version = "0.5.0"
description = "A port of liquid template engine for python"
authors = [ "pwwang <pwwang@pwwang.com>",]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pwwang/liquidpy"
repository = "https://github.com/pwwang/liquidpy"
[[tool.poetry.packages]]
include = ["liquid/*.py", "liquid/common/tags/tags.lark"]

[tool.poetry.dependencies]
python = "^3.6"
diot = "*"
lark-parser = "^0.8"
python-varname = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
